mysalon/templates/django-allauth-master/allauth/account/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
    path("logout/", views.logout, name="account_logout"),
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
]

mysalon/templates/django-allauth-master/allauth/urls.py
from importlib import import_module

from django.urls import include, path

from allauth.socialaccount import providers

from . import app_settings


urlpatterns = [path('', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [path('social/', include('allauth.socialaccount.urls'))]

# Provider urlpatterns, as separate attribute (for reusability).
provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns
urlpatterns += provider_urlpatterns

mysalon/urls.py
from django.urls import path,include
from .views import (
    HomeView,
    ItemDetailView,
   
)
app_name = 'mysalon'
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('home/',HomeView.as_view(),name='home'),
    path('product/<slug>/',ItemDetailView.as_view(),name="detail"),
    path('',views.posts,name="posts"),
    path('what_we_do/' ,views.what_we_do,name='what-we-do'),
    path('comment/<int:id>',views.add_comments,name='comment'),
    path('add-to-cart/<slug>/',views.add_to_cart,name='add-to-cart'),
    path('remove-from-cart/<slug>',views.remove_from_cart,name='remove_from_cart'),
    path('order_summary/',views.order_summary,name='order-summary'),
    path('remove_item/<slug>',views.remove_single_item_from_cart,name='remove_one'),
    path('create_appointment/',views.create_appointment,name="appointment"),
    path('paypal_return/',views.paypal_return,name="return"),
   
    #Dashboard
    path('activate/user/<int:user_id>', views.user_activate, name='activate_user'),
    path('deactivate/user/<int:user_id>', views.user_deactivate, name='deactivate_user'),
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('users/', views.registered_users, name='system_users'),
    
    #paypal
    path('go/',include,('paypal.standard.ipn.urls')),
    path('pay_total/',views.total_order,name='make_payment'),
]

salon/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('mysalon.urls')),
   
]

mysalon/models.py
from django.db import models
from django.conf import settings
from pyuploadcare.dj.models import ImageField
from django.contrib.auth.models import User
from django.urls import reverse



# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=None,null=True)
    pic = ImageField(blank=True,manual_crop='')
    bio = models.CharField(max_length=1000,blank=True,null=True)
    
    def __str__(self):
        return self.user.username
    
    def save_profile(self):
        return self.save()

CATEGORY_CHOICES = (
    ('SC', 'Skin Care'),
    ('HC', 'Hair Care'),
    ('PC', 'Personal Care'),
    ('F', 'Fragrances'),
    ('MK', 'Makeup'),
    ('MP', 'Manicure $ Pedicure'),
    ('S', 'suntan')
    
)
LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    image = ImageField(blank=True, manual_crop='')
    price = models.FloatField()
    discount_price = models.FloatField(blank=True,null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default='S')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default='P')
    slug = models.SlugField(default=None,null=True)
    description = models.TextField(default=None,null=True)
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('mysalon:detail',kwargs={
             'slug':self.slug
        })

    def get_add_to_cart_url(self):
        return reverse('mysalon:add-to-cart',kwargs={
            'slug':self.slug
        })
    def get_remove_from_cart_url(self):
        return reverse('mysalon:remove_from_cart',kwargs={
        'slug':self.slug
    })


class Appointment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=None,null=True)
    service = models.CharField(max_length=50)
    contact = models.CharField(max_length=15)
    email = models.EmailField()
    date = models.DateTimeField()
    
    def __str__(self):
        return self.service
    
    def save_appointment(self):
        return self.save()

    

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=None,null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price 
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class Salonposts(models.Model):
    name = models.CharField(max_length=30)
    pic = ImageField(blank=True, manual_crop='')
    price = models.FloatField()
    date = models.DateTimeField()

    @classmethod
    def get_one_post(cls, id):
        one_post = cls.objects.get(id=id)
        return one_post
    
    @classmethod
    def get_post_id(cls,postId):
        post_id=cls.objects.filter(id=postId)
        return post_id
    


class Comments(models.Model):
    comment = models.TextField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Salonposts, on_delete=models.CASCADE)

    def save_comment(self):
        return self.save()

    def __str__(self):

        return self.comment

    def get_comment(cls,id):
        comments = cls.objects.filter(salonpost_id__in=id)
        return comments
    
class Note(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    created_at = models.DateTimeField()
    created_by = models.CharField(max_length=50,blank=True,null=True)
    priority = models.IntegerField()
    

mysalon/templates/django-allauth-master/example/example/demo/views.py
# Create your views here.

mysalon/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View
from .models import *
from .forms import *
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import random


# Create your views here.


@login_required()
def item_list(request):
    context = {
        'item': Item.objects.all()
    }
    return render(request, 'homepage.html', context)

@login_required()
def item_list(request):
    context = {
        'item': Item.objects.all()
    }
    return render(request, 'homepage.html', context)

@login_required()
def order_summary(request):
    try:
        order = Order.objects.get(user=request.user,ordered=False)
        return render(request,'order_summary.html',{'object':order})
    except ObjectDoesNotExist:
        messages.warning(self.request,"You do not have an active order")
        
@login_required()       
def total_order(request):
    if request.method == 'POST':
        amount = request.POST.get('price')
        paypal_dict = {
            "business":settings.PAYPAL_RECEIVER_EMAIL,
            "amount":amount,
            "item_name":'Products',
            "invoice":str(random.randint(000,999)),
            "currency_code":'USD',
            "notify_url":' https://salonspa.herokuapp.com/go/',
            "return_url":'https://salonspa.herokuapp.com/payment-done',
            "cancel_return":'https://salonspa.herokuapp.com/payment-cancelled',
            
        }
        form = PayPalPaymentsForm(initial=paypal_dict)
        return render(request,'payment.html',{"form":form})
    else:
        messages.info(request,'Your payment was not successful, please try again')
        return render(request,'payment.html',{"form":form})
    
@login_required()
def jenga_payment(request):
    if request.method == 'POST':
        price = request.POST.get('amount')
        jenga_dict = {
            'token': 'xccuUjuysdsnvtloPWqiT',
            'merchantCode':str(random.randint(000,999)),
            'merchant': 'MerchantXYZ',
            'outletCode':str(random.randint(0,9) for iter in range(10)),
            'amount': 'price',
            'ez1_callback':'https/domain/'
        }
        
@csrf_exempt
def paypal_return(request):
    return render(request,"paypal_return.html")


class HomeView(ListView):
    model = Item
    paginated_by = 10
    template_name = 'homepage.html'

class ItemDetailView(DetailView):
    model = Item
    template_name = 'product.html'

@login_required()
def posts(request):
    
    return render(request, 'index.html')

def what_we_do(request):
    all_posts = Salonposts.objects.all()
    comments = Comments.objects.all()
    return render(request, 'posts.html', {'post': all_posts, 'comments': comments})


@login_required()
def add_comments(request, id):
    '''
    view function that renders one post and has a comment section
    '''
    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            post = Salonposts.objects.get(id=id)
            comment.post = post
            comment.save()
            return redirect('comment', id=id)
    else:
        form = AddCommentForm()
        post = Salonposts.get_one_post(id)
        posts = Salonposts.objects.get(id=id)
        comment = Comments.objects.filter(post=post.id)
        return render(request, 'comment.html', {'form': form, 'post': post, 'comments': comment})

@login_required()
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return redirect('mysalon:order-summary')
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return redirect("mysalon:detail", slug=slug)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("mysalon:detail", slug=slug)

@login_required()
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, "This item was removed from your cart.")
            return redirect('mysalon:order-summary')
        else:
            messages.info(request, "This item was not in your cart")
            return redirect('mysalon:detail', slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect('mysalon:detail', slug=slug)

@login_required()
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect('mysalon:order-summary')
        else:
            messages.info(request, "This item was not in your cart")
            return redirect('mysalon:detail', slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect('mysalon:detail', slug=slug)

@login_required()
def user_dashboard(request):
    """
    function for displaying dashboard
    """
    return render(request, 'dashboard.html')

@login_required()
def registered_users(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'users.html', context)

@login_required()
def user_deactivate(request, user_id):
    user = User.objects.get(pk=user_id)
    user.is_active = False
    user.save()
    messages.success(request, "User account has been successfully deactivated!")
    return redirect('system_users')

@login_required()
def user_activate(request, user_id):
    user = User.objects.get(pk=user_id)
    user.is_active = True
    user.save()
    messages.success(request, "User account has been successfully activated!")
    return redirect('system_users')

def create_appointment(request):
    user = request.user
    if request.method == 'POST':
        booked = Appointment.objects.all()
        for book in booked:
            if Appointment.user == request.user:
                messages.info(request,"You have a pending appointment")
                return redirect('mysalon:home')
        email = request.POST.get('email')
        number = request.POST.get('phone')
        date = request.POST.get('appointment')
        service = request.POST.get('service')
        
        
        if email and number and date and service:
            your_appointment = Appointment(user = request.user,email=email,contact=number,date=date,service=service)
            your_appointment.save()
            messages.info(request,"Your appointment has been scheduled on")
            return redirect('mysalon:home')
        else:
            messages.info(request,"Input all fields")
            return redirect('mysalon:appointment')
    else:
        messages.info(request,'Invalid Inputs, try again')
        return render(request,"appointments.html")
         
           
                
            
        
        

mysalon/templates/appointments.html
{% extends 'layout.html'%}
{%load bootstrap4%}
{%block content%}

<div class="container" >
    <div class="row">
   
    <div class="col-md-6">
        <div class="well">
       
            
            <div class="well-header" style = "padding-top:2em">BOOK ONLINE</div>
            <hr>
           <p class="header_p">Even though walk-ins are Welcome, 
            we encourage you to contact us via the form below to 
            set your appointment. You will be contacted within 24 hours 
            for confirmation.</p>
            <hr>
            <form  action="{% url 'mysalon:appointment'%}" method="POST">
                {% csrf_token%}
            <!-- Contact by Input -->    
            <div class="form-group1">
                <label for="inputemail"></label>
                <input type="phone" class="form-control" id="inputemail"  name="email" placeholder="Your Email">
            </div>
            
           <!-- Phone Input --> 
             <div class="form-group1">
                <label for="inputphone"></label>
                <input type="phone" class="form-control" id="inputphone" name = "phone" placeholder="Your Phone">
            </div>
            <hr>
          <!-- Appointment date -->  
            <p>Appointment Date:</p>
            
         <!-- 1st Choice Input --> 
        
        
             
        <div class="form-group">
            <label for="datepicer">Date Choice:</label>
            <div class="input-group date" id="datetimepicker8">
            <input type="date" class="form-control" name="appointment">
            <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
        </div>
        </div>
        
        
        <!-- Service Input -->
        <div class="form-group">
            <label for="Select" >Desired Service:</label>
            <select id="Select" name="service"class="form-control">
            <option>Braids &amp; Twist</option>
            <option>Clipper Cut</option>
            <option>Corrective Color</option>
            <option>Extensions Per Track</option>
            <option>Full Foil</option>
            <option>Haircolor</option>
            <option>Haircut</option>
            <option>Partial Foil</option>
            <option>Relaxer/Retouch</option>
            <option>Shampoo, Blow Dry or Se</option>
            
            </select>
        </div>
        
        <!-- Button Area-->
         <div class="checkbox">
                <label><input type="checkbox">Terms &amp; conditions</label>
            </div>
            
            <button type="submit" class="btn btn-info">Submit</button>
            <button type="submit" class="btn btn-danger">Cancel</button><hr>
            <span class="help-block">all appointments have $10 cancellation fee, thank you.</span>
        
         
         <!-- form end -->
         </form>
        </div><!-- well end -->
        </div>
    <div class="col-md-1"></div>
        <div class="col-md-4">
            <img src="https://images.pexels.com/photos/3373739/pexels-photo-3373739.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" >
        </div>
        <div class="col-md-2"></div>
    </div>

</div>
<style>



.well-header {
    font-size: 2em;
    font-weight: bold;
    font-family: helvetica Neue;
    color: #1E2749;
    
}

#disabledSelect{
    height: 30px;
}
/*
.form-control {
    height: 30px;
}
*/
.form-group1 {
    padding-bottom: 45px;
    height: 5px;
}



#disabledSelect{
    padding-bottom: 25px;
}

.input-group-addon,.fa> fa-calendar {
    color: #FFE071;
    background:  rgb(163, 183, 255);;
    border: solid 1px rgb(163, 183, 255);
}

p, label, checkbox {
    font-size: 1em;
    font-weight: bold;
    color: #1E2749;
    
}

.header_p {
    font-size: 1.2em;
}
/* 
.btn{
    color: rgba(198, 156, 0, 1);
    background:  rgb(163, 183, 255);;
    border: solid 1px  rgb(163, 183, 255);;
    ;
} */

.help-block {
    color:  rgb(36, 36, 37);;
}
</style>
{%endblock%}

mysalon/templates/homepage.html
{%extends 'layout.html'%}
{%load bootstrap4 %}
{% load static %}
{%block content%}

<div class="container-fluid" style="padding-top:4em; font-size: 20px;">

  <div class="row">
    {% for item in object_list %}
      <div class=col-md-3>
          <div class="card" style="margin-top: 20px;">
              <div class="card-title">
                  <h6 style="font-size: 20px;"><u><strong>{{item.title}}</strong></u></h6>
              </div>
              <a href="{{item.get_absolute_url}}">
                  <img class="img-fluid" src="{{item.image.cdn_url}}" alt=""></a>



              <div class="card-body">
                <a href="" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
              </div>
              <div class="card-footer">
                  <a href="{{item.discount_price}}">Discount:${{item.discount_price}}</a>
                  <p>${{item.price}}</p>
              </div>
      


          </div>
      </div>
      {%endfor%}
      <br><br>

  </div>


  <div class='col-md-2'></div>
</div>
<!--Section: Products v.3-->


<!--Pagination-->

<nav class="d-flex justify-content-center wow fadeIn">
  <ul class="pagination pg-blue">
   
    <!--Arrow left-->
    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.next_previous_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
   
    <li class="page-item active">
      <a class="page-link" href="?page={{page_obj.number}} ">{{page_obj.number}}
        <span class="sr-only"></span>
      </a>
    </li>

  
    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>

  </ul>
</nav>

<!--Pagination-->



{%endblock content%}

mysalon/templates/order_summary.html
 {%extends 'layout.html'%}

 {%block content%}

<div class="container" style="padding-top:6em">
    <div class="table-responsive text-nowrap">
        <h2>Order Summary</h2>
        <table class="table" style="font-size: 20px;">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Item title</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total Item Price</th>
              
             
            </tr>
          </thead>
          
              {%for order_item in object.items.all%}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{order_item.item.title}}</td>
              <td>{{order_item.item.price}}</td>
              <td><a href="{% url 'mysalon:remove_one' order_item.item.slug%}"><i class="fas fa-minus mr-2"></i>
            </a>{{order_item.quantity}}<a  href="{% url 'mysalon:add-to-cart' order_item.item.slug%}"><i class="fas fa-plus ml-2"></i></a></td>
              <td>{% if order_item.item.discount_price %}
              ${{order_item.get_total_discount_item_price}} 
              <span class='badge badge-info'>saved ${{order_item.get_amount_saved}}</span>
              {%else%}
              ${{order_item.get_total_item_price}}
              {%endif%}
              <a href="{% url 'mysalon:remove_from_cart' order_item.item.slug%}"><i class="fas fa-trash  float-right mr-2"></i>
            </td>
            

          </tr>
         
          <tr>
              {%empty%}
              <tr>
                  <td colspan='5'>Your cart is empty</td>
              </tr>
              <tr>
                <td colspan="5"><a href="" class="btn btn-info float-right ml-2">continue shopping</a>
                </td>
            </tr>
            {% endfor %}
            {%if object.get_total%}
            <td colspan='4'><u>Total:</u></td>
            <td><b>
              <form action="/pay_total/" method="POST">
                {%csrf_token%}
                <input type="hidden" value="{{object.get_total}}" name="price">
                ${{object.get_total}}
                <input type="submit" class="btn btn-warning" value="Pay">
  
              </form>


            </b></td>
        </tr>
        <tr>
            <td colspan="5"><a href="{% url 'mysalon:home'%}" class="btn btn-info float-right ml-2">continue shopping</a>
            </td>
        </tr>
        {%endif %}
          </tbody>
        </table>
      
      </div>
</div>
 {%endblock content%}

mysalon/templates/users.html
{% extends 'layout.html' %}
{% block content %}

    <div class="container-fluid" style="padding-top:5em">
        <div class="row">
      
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Registered Users</h1>
                </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <p class="bg-success" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                </ul>
            {% endif %}
                <table class="table">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">Username</th>
                      <th scope="col">Last login</th>
                      <th scope="col">Status</th>
                      <th scope="col">Date joined</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.username }}</td>
                            <td>{{ user.last_login }}</td>
                            <td>
                                {% if user.is_active %}
                                    <a   href="{% url 'mysalon:deactivate_user' user_id=user.id %}" class="btn btn-sm btn-danger">Deactivate</a>
                                    {% else %}
                                    <a href="{% url 'mysalon:activate_user' user_id=user.id %}" class="btn btn-sm btn-success">Activate</a>
                                {% endif %}
                            </td>
                            <td>{{ user.date_joined }}</td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </main>
        </div>
    </div>
{% endblock %}